CAST(MD5_BINARY(NULLIF(CONCAT_WS('||',
<<<<<<< HEAD
    IFNULL(NULLIF(UPPER(TRIM(CAST(CUSTOMER_ID AS VARCHAR))), ''), '^^')
), '^^')) AS BINARY(16)) AS CUSTOMER_PK
=======
    IFNULL(NULLIF(UPPER(TRIM(CAST("CUSTOMER_ID" AS VARCHAR))), ''), '^^')
), '^^')) AS BINARY(16)) AS "CUSTOMER_PK"
>>>>>>> dbtvault_update
