CAST(MD5_BINARY(CONCAT_WS('||',
<<<<<<< HEAD
    IFNULL(NULLIF(UPPER(TRIM(CAST(CUSTOMER_ID AS VARCHAR))), ''), '^^')
)) AS BINARY(16)) AS HASHDIFF
=======
    IFNULL(NULLIF(UPPER(TRIM(CAST("CUSTOMER_ID" AS VARCHAR))), ''), '^^')
)) AS BINARY(16)) AS "HASHDIFF"
>>>>>>> dbtvault_update
